packages:
  - account-ui
  - packages/*
  - site
  - '!packages/spring'
  - '!packages/spring-demo'
  - '!packages/spring-webflux'
  - '!packages/spring-webflux-demo'
ignoredBuiltDependencies:
  - sharp
